name: studentManagment API CI
on:
  push:
    branches:
      - master
      - feature/**
  pull_request:
    branches:
      - master
jobs:
  build-test-publish:
    name: Build, Test, and puplish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v5
      
      - name: setup .NET 8 SDK
        uses: actions/setup-dotnet@v5
        with: 
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore StudentManagement.API.sln

      - name: Build Solution
        run: dotnet build StudentManagement.API.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test StudentManagement.API.sln --configuration Release --no-build --verbosity normal

      - name: Publish Web API
        run: dotnet publish StudentManagement.API/StudentManagement.API.csproj --configuration Release --output ./publish --no-build 

      - name: Upload publish artifact
        uses: actions/upload-artifact@v6
        with:
          name: studentmanagement-api-publish
          path: ./publish
